function isValidId(id) {
    // Condition was generated by ChatGPT; validates that the id is a positive integer 
    return /^\d+$/.test(id);
}

function getValues(data, { forUpdate = false } = {}) {
    // Generated by ChatGPT; manipulats the request body for queries
    const keys = Object.keys(data).filter(k => data[k] !== undefined);
    const values = keys.map(k => data[k]);
    const placeholders = forUpdate
        ? keys.map(k => `${k} = ?`).join(', ')
        : keys.map(() => `?`).join(', ');

    return { keys, values, placeholders };
}

const Helper = { isValidId, getValues };
export default Helper;