import Joi from 'joi';

export const idSchema = Joi.object({
    id: Joi.number()
           .integer()
           .positive()
           .required()
});

// Generated by ChatGPT
export const productSchema = Joi.object({
    name: Joi.string()
             .min(1)
             .max(100)
             .required(),

    price: Joi.number()
              .positive()
              .precision(2)
              .min(0)
              .max(99999999.99)
              .required(),
              
    description: Joi.string()
                    .min(1)
                    .max(250)
                    .required(),
                    
    type: Joi.string()
             .valid('luxury', 'fashion', 'electronics', 'property', 'vehicle', 'collectible', 'other')
             .default('other')
});