import Joi from 'joi';

// Generated by ChatGPT

/**
 *  @description Product schema for the POST method.
 */
const createProductSchema = Joi.object({
    name: Joi.string()
             .min(1)
             .max(100)
             .required(),

    price: Joi.number()
              .precision(2)
              .min(0)
              .max(99999999.99)
              .required(),
              
    description: Joi.string()
                    .min(1)
                    .max(250)
                    .required(),
                    
    type: Joi.string()
             .valid('luxury', 'fashion', 'electronics', 'vehicle', 'collectible', 'other')
             .default('other'),
    
    brand: Joi.string()
              .min(1)
              .max(50)
              .default('unknown'),
    
    origin_loc: Joi.string()
                   .min(1)
                   .max(75)
                   .default('unknown'),

    stock_quantity: Joi.number()
                       .min(0)
                       .default(0)
});

/**
 *  @description Product schema for the PUT method.
 */
const updateProductSchema = Joi.object({
    name: Joi.string()
             .min(1)
             .max(100),

    price: Joi.number()
              .positive()
              .precision(2)
              .min(0)
              .max(99999999.99),
              
    description: Joi.string()
                    .min(1)
                    .max(250),
                    
    type: Joi.string()
             .valid('luxury', 'fashion', 'electronics', 'vehicle', 'collectible', 'other')
             .default('other'),

    brand: Joi.string()
              .min(1)
              .max(50)
              .default('unknown'),
    
    origin_loc: Joi.string()
                   .min(1)
                   .max(75)
                   .default('unknown'),

    stock_quantity: Joi.number()
                       .min(0)
                       .default(0)
});

const Schema = { createProductSchema, updateProductSchema };
export default Schema;